language: ruby
rvm:
  - 2.2.3
addons:
  postgresql: "9.3"

before_script:
  - git clone https://github.com/mezuro/kalibro_install.git -b v4.0 kalibro_install
  - pushd kalibro_install
    # Remove bugged libzmq3 package, see https://github.com/travis-ci/travis-ci/issues/982 and https://github.com/travis-ci/travis-ci/issues/1715 for details
  - sudo apt-get remove libzmq3
  - export KALIBRO_PROCESSOR_VERSION=v1.1.1
  - export KALIBRO_CONFIGURATIONS_VERSION=v1.2.0
  - bash install.sh
  - popd
  - cp config/database.yml.sample config/database.yml
  - bundle exec rake db:setup
  - cp features/support/kalibro_cucumber_helpers.yml.sample features/support/kalibro_cucumber_helpers.yml
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - export CODECLIMATE_REPO_TOKEN=045c2433d496f108c0c6afa5516a72ddbfb1868fb34bf7a9bd095b7a0ea34a79

script:
  - bundle exec rake spec
  - bundle exec rake konacha:run
  - bundle exec rake cucumber

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
