language: ruby
rvm:
  - 2.1.1

before_script:
  - "cp config/database.yml.sample config/database.yml"
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - git clone https://gist.github.com/0c4ad3b5700c6364abf1.git kalibro_install
  - pushd kalibro_install
  - bash install.sh
  - popd
  - cp features/support/kalibro_cucumber_helpers.yml.sample features/support/kalibro_cucumber_helpers.yml
  - git clone https://github.com/mezuro/kalibro_gatekeeper.git
  - pushd kalibro_gatekeeper
  - cp config/database.yml.sample config/database.yml
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install
  - bundle exec rails s -p 8081 -d
  - popd
  - export BUNDLE_GEMFILE=$PWD/Gemfile

script:
  - sudo service tomcat6 stop
  - bundle exec rake spec
  - bundle exec rake konacha:run
  - sudo service tomcat6 start
  - bundle exec rake cucumber

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
