language: ruby
rvm:
  - 2.3.0
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 045c2433d496f108c0c6afa5516a72ddbfb1868fb34bf7a9bd095b7a0ea34a79
before_install:
  - gem update bundler
  # Remove bugged libzmq3 package, nsee https://github.com/travis-ci/travis-ci/issues/982 and https://github.com/travis-ci/travis-ci/issues/1715 for details
  - sudo apt-get remove libzmq3
  - git clone https://github.com/mezuro/kalibro_install.git -b v4.1 kalibro_install
  - export KALIBRO_PROCESSOR_VERSION=v1.1.10 KALIBRO_CONFIGURATIONS_VERSION=v2.0.1
  - export KALIBRO_PROCESSOR_START=0 KALIBRO_CONFIGURATIONS_START=0
  - ./kalibro_install/install.sh
before_script:
  - gem install foreman
  - cp config/database.yml.sample config/database.yml
  - cp features/support/kalibro_cucumber_helpers.yml.sample features/support/kalibro_cucumber_helpers.yml
  - export BUNDLE_GEMFILE=$PWD/Gemfile
script:
  - bundle exec rake spec
  - bundle exec rake konacha:run
  - foreman start -f kalibro_configurations/Procfile &
  - foreman start -f kalibro_processor/Procfile &
  - bundle exec rake cucumber
notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
