language: ruby
rvm:
  - 2.0.0-p247

before_script:
  - "cp config/database.yml.sample config/database.yml"
  - "rake db:migrate RAILS_ENV=test"

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
